apply plugin: 'com.android.library'

android {
    namespace 'com.sakarrobotics.c40agent.robot'
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':sdk')
    implementation project(':navigation')
    implementation project(':charging')
    implementation project(':telemetry')
    implementation project(':logging')
}
