apply plugin: 'com.android.library'

android {
    namespace 'com.sakarrobotics.c40agent.diagnostics'
    compileSdk 34

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
